# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chairtable' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chairtable
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'chairtableTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
