# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chairtable' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chairtable
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  # Flexbox Layout Manager Used By React Natve
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

  # React Native
  pod 'React', path: '../node_modules/react-native', subspecs: [

  # Comment out any unneeded subspecs to reduce bundle size.
  'Core',
  ‘BatchedBridge',
#  'DevSupport',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTBlob',
#  'RCTCameraRoll',
  'RCTGeolocation',
  'RCTImage',
  'RCTNetwork',
#  'RCTPushNotification',
  'RCTSettings',
#  'RCTTest',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  'RCTLinkingIOS'
  ]

  # Mapbox
  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'

  target 'chairtableTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
